### ISSUE TITLE
hid_field_extract() called with n (64) > 32!

### ISSUE THREAD

**Issue by Dunedan** [roadrunner2/macbook12-spi-driver#16]
Since the split of the drivers I regularly see messages like the following one in the logs:
```
[ 2391.090155] apple-ibridge-hid 0003:05AC:8600.0002: hid_field_extract() called with n (64) > 32! (swapper/0)
```

I suppose that's not intentional?

**Comment by roadrunner2** [comment]
Well, no, it's not "intentional", but a limitation in the hid report parsing code: the author seemed to think there would never be reports with fields wider than 32 bits (and the relevant functions all return a `u32`), but a couple of the T1's reports do in fact have 64-bit fields; and one of them is an input report that the device sends every now and then, triggering the above warning.

The meaning of that report is currently unknown to me, so it's just ignored, and therefore the limitation and warning are harmless at this point in time.ut

Btw., are you sure it didn't show up before the split? I thought it was related to the ALS stuff, but could certainly be wrong.

**Comment by Dunedan** [comment]
Not entirely sure, but I didn't notice such messages before.

**Comment by Dunedan** [comment]
Speaking of the ALS driver: I can only force-unload the kernel module. Any way around that?

**Comment by roadrunner2** [comment]
> Speaking of the ALS driver: I can only force-unload the kernel module. Any way around that?

Ah, yes: you need to release the iio buffer and trigger first (in that order no less):
```sh
echo 0 | sudo tee /sys/bus/iio/devices/iio:device*/buffer/enable
echo '' | sudo tee /sys/bus/iio/devices/iio:device*/trigger/current_trigger
```

**Comment by Dunedan** [comment]
Those commands work for me to be able to unforcefully remove the ALS module. :+1:

Back to the original topic: If we can ignore these warnings I guess we can close this issue as well? Or is there a point in trying to get that changed upstream?

**Comment by roadrunner2** [comment]
> Back to the original topic: If we can ignore these warnings I guess we can close this issue as well? Or is there a point in trying to get that changed upstream?

I took a look again, and from my reading of [the spec](https://www.usb.org/sites/default/files/documents/hid1_11.pdf) it looks like 64-bit fields aren't actually allowed, so I've added some patching of the reports to replace these with 32-bit fields, which avoids the warnings in the logs.
