### ISSUE TITLE
Not working on MBP15,2 13"

### ISSUE THREAD

**Issue by Serizao** [roadrunner2/macbook12-spi-driver#19]
Hello,
I had try  to install this driver but it not work. At the beginnning i thinked it's my installation but i have tried this https://foolcontrol.org/?p=2952 and it not work too. If you want something for search the bug tell me. And thank you very munch for all work on this drivers :)

**Comment by roadrunner2** [comment]
That is correct: the MBP15,* models are not supported at all currently, due to the keyboard, trackpad, touchbar, light sensors, etc all hanging off the new T2 chip and nobody having reverse engineered a driver for that chip yet. Furthermore, if/when somebody does, the keyboard/trackpad driver here will probably not be necessary, is it appears they show up as usb devices again on these machines.

For more info on the progress of getting MBP15,* models working, see Dunedan/mbp-2016-linux#71.
